/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleMapInPlace;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'GradleMapInPlace.greeting' plugin.
 */
class GradleMapInPlacePluginTest {
    @Test
    void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("GradleMapInPlace.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }

    @Test
    void mapInPlace() {
        var mapInPlace = new PropertyMapInPlace<String>() {};
        mapInPlace.set("value");
        mapInPlace.mapInPlace((value) -> value + "-something");
        assert mapInPlace.getCurrentValue().equals("value");
        assert mapInPlace.getFinalValue().equals("value-something");
    }
}
